export const typography = {
  font: {
    sans: '"Inter", sans-serif',
  },
  weight: {
    regular: "400",
    bold: "700",
    semiBold: "600",
    medium: "500",
  },
  spacing: {
    large: "0.15px",
    default: "0px",
    xlarge: "0.25px",
  },
  heading: {
    small600: {
      fontFamily: "{typography.font.sans}",
      fontSize: "{space.scale.24}",
      fontWeight: "{typography.weight.semiBold}",
      lineHeight: "{space.scale.32}",
      letterSpacing: "{typography.spacing.default}",
    },
    default600: {
      fontFamily: "{typography.font.sans}",
      fontSize: "{space.scale.32}",
      fontWeight: "{typography.weight.semiBold}",
      letterSpacing: "{typography.weight.semiBold}",
      lineHeight: "{space.scale.40}",
    },
  },
  label: {
    xlarge500: {
      fontFamily: "{typography.font.sans}",
      fontSize: "22",
      fontWeight: "{typography.weight.medium}",
      lineHeight: "{space.scale.28}",
      letterSpacing: "{typography.spacing.default}",
    },
    xlarge400: {
      fontFamily: "{typography.font.sans}",
      fontSize: "22",
      fontWeight: "{typography.weight.regular}",
      lineHeight: "{space.scale.28}",
      letterSpacing: "{typography.spacing.default}",
    },
    large500: {
      fontFamily: "{typography.font.sans}",
      fontSize: "18",
      fontWeight: "{typography.weight.medium}",
      letterSpacing: "{typography.spacing.default}",
      lineHeight: "{space.scale.24}",
    },
    large400: {
      fontFamily: "{typography.font.sans}",
      fontSize: "18",
      fontWeight: "{typography.weight.regular}",
      letterSpacing: "{typography.spacing.default}",
      lineHeight: "{space.scale.24}",
    },
    default400: {
      fontFamily: "{typography.font.sans}",
      fontSize: "{space.scale.16}",
      fontWeight: "{typography.weight.regular}",
      letterSpacing: "",
      lineHeight: "{space.scale.20}",
    },
    default500: {
      fontFamily: "{typography.font.sans}",
      fontSize: "{space.scale.16}",
      fontWeight: "{typography.weight.medium}",
      letterSpacing: "{space.scale.0}",
      lineHeight: "{space.scale.20}",
    },
    small400: {
      fontFamily: "{typography.font.sans}",
      fontSize: "14",
      fontWeight: "{typography.weight.regular}",
      letterSpacing: "{typography.spacing.large}",
      lineHeight: "{space.scale.16}",
    },
    small500: {
      fontFamily: "{typography.font.sans}",
      fontSize: "14",
      fontWeight: "{typography.weight.medium}",
      letterSpacing: "{typography.spacing.large}",
      lineHeight: "{space.scale.16}",
    },
    xsmall400: {
      fontFamily: "{typography.font.sans}",
      fontSize: "12",
      fontWeight: "{typography.weight.regular}",
      letterSpacing: "{typography.spacing.xlarge}",
      lineHeight: "{space.scale.16}",
    },
    xsmall500: {
      fontFamily: "{typography.font.sans}",
      fontSize: "12",
      fontWeight: "{typography.weight.medium}",
      letterSpacing: "{typography.spacing.xlarge}",
      lineHeight: "{space.scale.16}",
    },
  },
  body: {
    default400: {
      fontFamily: "{typography.font.sans}",
      fontSize: "{space.scale.16}",
      fontWeight: "{typography.weight.regular}",
      lineHeight: "{space.scale.24}",
    },
    default500: {
      fontFamily: "{typography.font.sans}",
      fontSize: "{space.scale.16}",
      fontWeight: "{typography.weight.medium}",
      lineHeight: "{space.scale.24}",
    },
    large400: {
      fontFamily: "{typography.font.sans}",
      fontSize: "18",
      fontWeight: "{typography.weight.regular}",
      lineHeight: "{space.scale.28}",
    },
    large500: {
      fontFamily: "{typography.font.sans}",
      fontSize: "18",
      fontWeight: "{typography.weight.medium}",
      lineHeight: "{space.scale.28}",
    },
  },
};
